alter table CACHACA_PRODUCAO add constraint FK_CACHACA_PRODUCAO_ID_PRODUTO foreign key (ID_PRODUTO_ID) references CACHACA_PRODUTO(ID);
create index IDX_CACHACA_PRODUCAO_ID_PRODUTO on CACHACA_PRODUCAO (ID_PRODUTO_ID);
