alter table CACHACA_PRODUTO add constraint FK_CACHACA_PRODUTO_CATEGORIA foreign key (CATEGORIA_ID) references CACHACA_CATEGORIA(ID);
create index IDX_CACHACA_PRODUTO_CATEGORIA on CACHACA_PRODUTO (CATEGORIA_ID);
