alter table CACHACA_CLIENTE add constraint FK_CACHACA_CLIENTE_ID_ESTADO foreign key (ID_ESTADO_ID) references CACHACA_ESTADO(ID);
create index IDX_CACHACA_CLIENTE_ID_ESTADO on CACHACA_CLIENTE (ID_ESTADO_ID);
