alter table CACHACA_PRODUTO_VENDA add constraint FK_CACHACA_PRODUTO_VENDA_ID_VENDA foreign key (ID_VENDA_ID) references CACHACA_VENDA(ID);
alter table CACHACA_PRODUTO_VENDA add constraint FK_CACHACA_PRODUTO_VENDA_ID_PRODUTO foreign key (ID_PRODUTO_ID) references CACHACA_PRODUTO(ID);
create index IDX_CACHACA_PRODUTO_VENDA_ID_VENDA on CACHACA_PRODUTO_VENDA (ID_VENDA_ID);
create index IDX_CACHACA_PRODUTO_VENDA_ID_PRODUTO on CACHACA_PRODUTO_VENDA (ID_PRODUTO_ID);
