alter table CACHACA_PRODUTO_VENDA add constraint FK_CACHACA_PRODUTO_VENDA_VENDA foreign key (VENDA_ID) references CACHACA_VENDA(ID);
create index IDX_CACHACA_PRODUTO_VENDA_VENDA on CACHACA_PRODUTO_VENDA (VENDA_ID);
