alter table CACHACA_PRODUCAO add constraint FK_CACHACA_PRODUCAO_PRODUTO foreign key (PRODUTO_ID) references CACHACA_PRODUTO(ID);
create index IDX_CACHACA_PRODUCAO_PRODUTO on CACHACA_PRODUCAO (PRODUTO_ID);
