alter table CACHACA_PRODUCAO add constraint FK_CACHACA_PRODUCAO_INSUMO foreign key (INSUMO_ID) references CACHACA_INSUMOS(ID);
create index IDX_CACHACA_PRODUCAO_INSUMO on CACHACA_PRODUCAO (INSUMO_ID);
