alter table CACHACA_BARRICA add constraint FK_CACHACA_BARRICA_PRODUTO foreign key (PRODUTO_ID) references CACHACA_PRODUTO(ID);
create index IDX_CACHACA_BARRICA_PRODUTO on CACHACA_BARRICA (PRODUTO_ID);
