alter table CACHACA_INSUMO_PRODUTO add constraint FK_CACHACA_INSUMO_PRODUTO_INSUMO foreign key (INSUMO_ID) references CACHACA_INSUMO(ID);
create index IDX_CACHACA_INSUMO_PRODUTO_INSUMO on CACHACA_INSUMO_PRODUTO (INSUMO_ID);
