alter table CACHACA_BARRICA_PRODUTO add constraint FK_CACHACA_BARRICA_PRODUTO_PRODUTO foreign key (PRODUTO_ID) references CACHACA_PRODUTO(ID);
alter table CACHACA_BARRICA_PRODUTO add constraint FK_CACHACA_BARRICA_PRODUTO_BARRICA foreign key (BARRICA_ID) references CACHACA_BARRICA(ID);
create index IDX_CACHACA_BARRICA_PRODUTO_PRODUTO on CACHACA_BARRICA_PRODUTO (PRODUTO_ID);
create index IDX_CACHACA_BARRICA_PRODUTO_BARRICA on CACHACA_BARRICA_PRODUTO (BARRICA_ID);
