-- begin CACHACA_PRODUTO
alter table CACHACA_PRODUTO add constraint FK_CACHACA_PRODUTO_CATEGORIA foreign key (CATEGORIA_ID) references CACHACA_CATEGORIA(ID)^
create index IDX_CACHACA_PRODUTO_CATEGORIA on CACHACA_PRODUTO (CATEGORIA_ID)^
-- end CACHACA_PRODUTO
-- begin CACHACA_VENDA
alter table CACHACA_VENDA add constraint FK_CACHACA_VENDA_ID_CLIENTE foreign key (ID_CLIENTE_ID) references CACHACA_CLIENTE(ID)^
create index IDX_CACHACA_VENDA_ID_CLIENTE on CACHACA_VENDA (ID_CLIENTE_ID)^
-- end CACHACA_VENDA
-- begin CACHACA_PRODUTO_VENDA
alter table CACHACA_PRODUTO_VENDA add constraint FK_CACHACA_PRODUTO_VENDA_ID_PRODUTO foreign key (ID_PRODUTO_ID) references CACHACA_PRODUTO(ID)^
alter table CACHACA_PRODUTO_VENDA add constraint FK_CACHACA_PRODUTO_VENDA_VENDA foreign key (VENDA_ID) references CACHACA_VENDA(ID)^
create index IDX_CACHACA_PRODUTO_VENDA_ID_PRODUTO on CACHACA_PRODUTO_VENDA (ID_PRODUTO_ID)^
create index IDX_CACHACA_PRODUTO_VENDA_VENDA on CACHACA_PRODUTO_VENDA (VENDA_ID)^
-- end CACHACA_PRODUTO_VENDA
-- begin CACHACA_PRODUCAO
alter table CACHACA_PRODUCAO add constraint FK_CACHACA_PRODUCAO_PRODUTO foreign key (PRODUTO_ID) references CACHACA_PRODUTO(ID)^
create index IDX_CACHACA_PRODUCAO_PRODUTO on CACHACA_PRODUCAO (PRODUTO_ID)^
-- end CACHACA_PRODUCAO
-- begin CACHACA_INSUMO_PRODUTO
alter table CACHACA_INSUMO_PRODUTO add constraint FK_CACHACA_INSUMO_PRODUTO_PRODUTO foreign key (PRODUTO_ID) references CACHACA_PRODUTO(ID)^
alter table CACHACA_INSUMO_PRODUTO add constraint FK_CACHACA_INSUMO_PRODUTO_INSUMO foreign key (INSUMO_ID) references CACHACA_INSUMO(ID)^
create index IDX_CACHACA_INSUMO_PRODUTO_PRODUTO on CACHACA_INSUMO_PRODUTO (PRODUTO_ID)^
create index IDX_CACHACA_INSUMO_PRODUTO_INSUMO on CACHACA_INSUMO_PRODUTO (INSUMO_ID)^
-- end CACHACA_INSUMO_PRODUTO
-- begin CACHACA_BARRICA
alter table CACHACA_BARRICA add constraint FK_CACHACA_BARRICA_PRODUTO foreign key (PRODUTO_ID) references CACHACA_PRODUTO(ID)^
create index IDX_CACHACA_BARRICA_PRODUTO on CACHACA_BARRICA (PRODUTO_ID)^
-- end CACHACA_BARRICA
-- begin CACHACA_BARRICA_PRODUTO
alter table CACHACA_BARRICA_PRODUTO add constraint FK_CACHACA_BARRICA_PRODUTO_PRODUTO foreign key (PRODUTO_ID) references CACHACA_PRODUTO(ID)^
alter table CACHACA_BARRICA_PRODUTO add constraint FK_CACHACA_BARRICA_PRODUTO_BARRICA foreign key (BARRICA_ID) references CACHACA_BARRICA(ID)^
create index IDX_CACHACA_BARRICA_PRODUTO_PRODUTO on CACHACA_BARRICA_PRODUTO (PRODUTO_ID)^
create index IDX_CACHACA_BARRICA_PRODUTO_BARRICA on CACHACA_BARRICA_PRODUTO (BARRICA_ID)^
-- end CACHACA_BARRICA_PRODUTO
