-- begin CACHACA_PRODUTO
alter table CACHACA_PRODUTO add constraint FK_CACHACA_PRODUTO_ID_CATEGORIA foreign key (ID_CATEGORIA_ID) references CACHACA_CATEGORIA(ID)^
create index IDX_CACHACA_PRODUTO_ID_CATEGORIA on CACHACA_PRODUTO (ID_CATEGORIA_ID)^
-- end CACHACA_PRODUTO
-- begin CACHACA_CLIENTE
alter table CACHACA_CLIENTE add constraint FK_CACHACA_CLIENTE_ID_ESTADO foreign key (ID_ESTADO_ID) references CACHACA_ESTADO(ID)^
create index IDX_CACHACA_CLIENTE_ID_ESTADO on CACHACA_CLIENTE (ID_ESTADO_ID)^
-- end CACHACA_CLIENTE
-- begin CACHACA_VENDA
alter table CACHACA_VENDA add constraint FK_CACHACA_VENDA_ID_CLIENTE foreign key (ID_CLIENTE_ID) references CACHACA_CLIENTE(ID)^
create index IDX_CACHACA_VENDA_ID_CLIENTE on CACHACA_VENDA (ID_CLIENTE_ID)^
-- end CACHACA_VENDA
-- begin CACHACA_PRODUTO_VENDA
alter table CACHACA_PRODUTO_VENDA add constraint FK_CACHACA_PRODUTO_VENDA_ID_VENDA foreign key (ID_VENDA_ID) references CACHACA_VENDA(ID)^
alter table CACHACA_PRODUTO_VENDA add constraint FK_CACHACA_PRODUTO_VENDA_ID_PRODUTO foreign key (ID_PRODUTO_ID) references CACHACA_PRODUTO(ID)^
create index IDX_CACHACA_PRODUTO_VENDA_ID_VENDA on CACHACA_PRODUTO_VENDA (ID_VENDA_ID)^
create index IDX_CACHACA_PRODUTO_VENDA_ID_PRODUTO on CACHACA_PRODUTO_VENDA (ID_PRODUTO_ID)^
-- end CACHACA_PRODUTO_VENDA
-- begin CACHACA_PRODUCAO
alter table CACHACA_PRODUCAO add constraint FK_CACHACA_PRODUCAO_PRODUTO foreign key (PRODUTO_ID) references CACHACA_PRODUTO(ID)^
create index IDX_CACHACA_PRODUCAO_PRODUTO on CACHACA_PRODUCAO (PRODUTO_ID)^
-- end CACHACA_PRODUCAO
