-- begin CACHACA_PRODUTO
alter table CACHACA_PRODUTO add constraint FK_CACHACA_PRODUTO_CATEGORIA foreign key (CATEGORIA_ID) references CACHACA_CATEGORIA(ID)^
create index IDX_CACHACA_PRODUTO_CATEGORIA on CACHACA_PRODUTO (CATEGORIA_ID)^
-- end CACHACA_PRODUTO
-- begin CACHACA_CLIENTE
alter table CACHACA_CLIENTE add constraint FK_CACHACA_CLIENTE_ESTADO foreign key (ESTADO_ID) references CACHACA_ESTADO(ID)^
create index IDX_CACHACA_CLIENTE_ESTADO on CACHACA_CLIENTE (ESTADO_ID)^
-- end CACHACA_CLIENTE
